trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureWebAppServiceConnection'
  appName: 'myapp98600'
  appPlan: 'ASP-webapp-899e'
  packagePath: '$(System.DefaultWorkingDirectory)/path/to/your/package.zip'

stages:
  - stage: Deploy
    displayName: 'Azure Web App Deployment'

    jobs:
      - job: DeployWebApp
        displayName: 'Deploy Web App'

        steps:
          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App'
            inputs:
              azureSubscription: '$(azureServiceConnection)'
              appType: 'webAppLinux'
              appName: '$(appName)'
              package: '$(packagePath)'