apiVersion: v1
kind: Service

metadata:
  name: pythonwebapp-service

spec:
  type: LoadBalancer

  selector:
    app: pythonwebapp

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
